import { Product } from "@/types/product.type";

export const mockedProducts: Product[] = [
  {
    id: "p1",
    title: "Крапельна стрічка 16 мм, 6 mil, 20 см",
    price: 12,
    image: "/images/kapelna-strichka.webp",
    inStock: true,
  },
  {
    id: "p2",
    title: "Крапельна стрічка 16 мм, 8 mil, 30 см",
    price: 16,
    image: null,
    inStock: true,
  },
  {
    id: "p3",
    title: "Крапельна трубка 16 мм, бухта 100 м",
    price: 980,
    image: null,
    inStock: false,
  },
  {
    id: "p4",
    title: "Крапельна трубка 20 мм, бухта 50 м",
    price: 740,
    image: null,
    inStock: true,
  },
  {
    id: "p5",
    title: 'Фільтр дисковий 1" для систем поливу',
    price: 420,
    image: "/images/kapelna-strichka.webp",
    inStock: false,
  },
  {
    id: "p6",
    title: 'Фільтр сітчастий 3/4"',
    price: 260,
    image: null,
    inStock: false,
  },
  {
    id: "p7",
    title: "Кран стартовий з гумкою 16 мм",
    price: 18,
    image: null,
    inStock: false,
  },
  {
    id: "p8",
    title: "Стартер з краном для крапельної стрічки",
    price: 28,
    image: null,
    inStock: false,
  },
  {
    id: "p9",
    title: "Заглушка для крапельної трубки 16 мм",
    price: 6,
    image: "/images/kapelna-strichka.webp",
    inStock: false,
  },
  {
    id: "p10",
    title: "Трійник 16 мм для систем крапельного поливу",
    price: 12,
    image: null,
    inStock: false,
  },
  {
    id: "p11",
    title: "Коліно 16 мм",
    price: 9,
    image: null,
    inStock: false,
  },
  {
    id: "p12",
    title: "Муфта ремонтна 16 мм",
    price: 11,
    image: null,
    inStock: false,
  },
  {
    id: "p13",
    title: "Мікроджет 360°",
    price: 22,
    image: null,
    inStock: false,
  },
  {
    id: "p14",
    title: "Мікроспринклер 180°",
    price: 26,
    image: null,
    inStock: true,
  },
  {
    id: "p15",
    title: "Таймер поливу механічний",
    price: 690,
    image: null,
    inStock: false,
  },
  {
    id: "p16",
    title: "Таймер поливу електронний",
    price: 1490,
    image: null,
    inStock: false,
  },
  {
    id: "p17",
    title: "Редуктор тиску 1 бар",
    price: 310,
    image: null,
    inStock: true,
  },
  {
    id: "p18",
    title: "Редуктор тиску 2 бари",
    price: 340,
    image: null,
    inStock: false,
  },
  {
    id: "p19",
    title: 'Кран кульовий 1"',
    price: 180,
    image: null,
    inStock: false,
  },
  {
    id: "p20",
    title: 'Кран кульовий 3/4"',
    price: 140,
    image: null,
    inStock: false,
  },
];
